### ISSUE TITLE
Ensembl 91-92 comparison for human

### ISSUE THREAD

**Issue by egonw** [bridgedb/create-bridgedb-genedb#17]
QS output created by @LucDM:

```
WARNING: Rf is only in old database
WARNING: Il is only in old database
WARNING: Ag is only in old database
WARNING: Uc is only in old database
WARNING: U is only in old database
WARNING: T is only in old database
WARNING: Om is only in old database
WARNING: X is only in old database
INFO: Number of ids in Mb (miRBase Sequence): 1881 (unchanged)
INFO: Hac is only in new database
INFO: Number of ids in Hac: 37387
INFO: Number of ids in S (Uniprot-TrEMBL): 73653 (299 added, 243 removed -> overall changed +0.1%)
INFO: Number of ids in En (Ensembl): 58336 (237 added, 144 removed -> overall changed +0.2%)
INFO: Number of ids in Pd (PDB): 35342 (1340 added, 16 removed -> overall changed +3.9%)
INFO: Number of ids in Wg (WikiGenes): 19348 (131 added, 6202 removed -> overall changed -23.9%)
WARNING: Number of ids in Wg has shrunk by more than 10%
INFO: Number of ids in L (Entrez Gene): 19348 (131 added, 6202 removed -> overall changed -23.9%)
WARNING: Number of ids in L has shrunk by more than 10%
INFO: Number of ids in Q (RefSeq): 102298 (747 added, 1339 removed -> overall changed -0.6%)
INFO: Number of ids in H (HGNC): 37387 (251 added, 153 removed -> overall changed +0.3%)
INFO: Attribute provided: Type
INFO: Attribute provided: Description
INFO: Attribute provided: Symbol
INFO: Attribute provided: Chromosome
INFO: new size is 173 Mb (changed -59.7%)
INFO: total number of identifiers is 384980
INFO: total number of mappings is 397366
```

(I removed the secondary ID checks)

**Comment by egonw** [comment]
@LucDM, the removal of a number of databases is intentional (you can find their codes here: https://github.com/bridgedb/datasources/blob/main/datasources.tsv).

I forgot what was up with these two drops:

```
INFO: Number of ids in Wg (WikiGenes): 19348 (131 added, 6202 removed -> overall changed -23.9%)
WARNING: Number of ids in Wg has shrunk by more than 10%
INFO: Number of ids in L (Entrez Gene): 19348 (131 added, 6202 removed -> overall changed -23.9%)
WARNING: Number of ids in L has shrunk by more than 10%
```

**Comment by LucDM** [comment]
So if I understand correctly, we are good-to-go and I can proceed with the updates? In which case I will do Hs completely to current.  Re-running them in case necessary is no big deal.

**Comment by egonw** [comment]
You can go ahead with later Ensembl releases for Human, yes, if that is what you mean.

**Comment by LucDM** [comment]
All Hs updates have been done upto current.
Files are on surfdrive:
[https://surfdrive.surf.nl/files/index.php/apps/files?dir=/shared-ALL/ensembl/Hs](https://surfdrive.surf.nl/files/index.php/apps/files?dir=/shared-ALL/ensembl/Hs)

This is the shared dir containing the screendumps-file (to check the error-messages) and all the .bridge and the .QC files for you to check.

@egonw @mkutmon you both have all rights to the shared-ALL folder so you should not have a problem accessing these.

**Comment by Chris-Evelo** [comment]
I think I cannot access that folder? At least it tells me it doesn't exist.

**Comment by LucDM** [comment]
Goedemorgen Chris,

Ik heb de surfdrive map vrijgeschakeld voor je met alle rechten.
Probeer nog eens en als het niet lukt dan even laten weten uiteraard.

Mvg
Luc
