### ISSUE TITLE
src/main/resource/BioMartSources.tsv needs to be updated

### ISSUE THREAD

**Issue by nunogit** [bridgedb/create-bridgedb-genedb#8]
All these are not present. In principle BioMartSources needs to be updated. Please analyze

affy_hc_g110 not present in BioMartSources file (BioMartSources.tsv)
affy_hg_focus not present in BioMartSources file (BioMartSources.tsv)
affy_hg_u133a_2 not present in BioMartSources file (BioMartSources.tsv)
affy_hg_u133a not present in BioMartSources file (BioMartSources.tsv)
affy_hg_u133b not present in BioMartSources file (BioMartSources.tsv)
affy_hg_u133_plus_2 not present in BioMartSources file (BioMartSources.tsv)
affy_hg_u95av2 not present in BioMartSources file (BioMartSources.tsv)
affy_hg_u95b not present in BioMartSources file (BioMartSources.tsv)
affy_hg_u95c not present in BioMartSources file (BioMartSources.tsv)
affy_hg_u95d not present in BioMartSources file (BioMartSources.tsv)
affy_hg_u95e not present in BioMartSources file (BioMartSources.tsv)
affy_hg_u95a not present in BioMartSources file (BioMartSources.tsv)
affy_primeview not present in BioMartSources file (BioMartSources.tsv)
affy_hugenefl not present in BioMartSources file (BioMartSources.tsv)
affy_hugene_1_0_st_v1 not present in BioMartSources file (BioMartSources.tsv)
affy_hugene_2_0_st_v1 not present in BioMartSources file (BioMartSources.tsv)
efg_agilent_sureprint_g3_ge_8x60k not present in BioMartSources file (BioMartSources.tsv)
efg_agilent_sureprint_g3_ge_8x60k_v2 not present in BioMartSources file (BioMartSources.tsv)
efg_agilent_wholegenome_4x44k_v1 not present in BioMartSources file (BioMartSources.tsv)
efg_agilent_wholegenome_4x44k_v2 not present in BioMartSources file (BioMartSources.tsv)
agilent_cgh_44b not present in BioMartSources file (BioMartSources.tsv)
illumina_humanwg_6_v1 not present in BioMartSources file (BioMartSources.tsv)
illumina_humanwg_6_v2 not present in BioMartSources file (BioMartSources.tsv)
illumina_humanwg_6_v3 not present in BioMartSources file (BioMartSources.tsv)
illumina_humanht_12_v3 not present in BioMartSources file (BioMartSources.tsv)
illumina_humanht_12_v4 not present in BioMartSources file (BioMartSources.tsv)

**Comment by drlrc** [comment]
I am not sure how the file BioMartSources.tsv was obtained. I do know that Biomart (at least via the biomaRt R interface) has a very unstable interface - calls may or may not work, and - worse - may only lead to partial retrieved results without giving an error message. So maybe an incomplete file was retrieved using an API...
All these fields to external (probe/probeset) references should in fact be present in the Biomart tables, expect for the agilent field starting with 'efg' that (generally) are without 'efg'.

**Comment by Chris-Evelo** [comment]
I thought that that was indeed a reason to download the file as a whole and not get it from the BioMart api. Nuno, are we no longer doing that?

**Comment by egonw** [comment]
@JonathanMELIUS, can you please document here how content of `BioMartSources.tsv` was obtained and how it can/should be updated?

**Comment by nunogit** [comment]
@JonathanMELIUS and I had a meeting where he explained that the file https://github.com/bridgedb/create-bridgedb-genedb/blob/master/src/main/java/script/QueryBioMart.java
needs to be updated.
There was a change in the ensenbl biomart  format. We can make it more generic by comparing case insensitive.

Note @nunogit: add documentation about BioMartSources.tsv and the relation with this code (dynamically includes new sources)

**Comment by egonw** [comment]
Both, thanks for meeting up!

**Comment by egonw** [comment]
Done: https://github.com/bridgedb/create-bridgedb-genedb/commit/1b9a1ace86e54af5d4a8ec1c7e72c5c81193cf9b
