### ISSUE TITLE
Check if BioMartSources is present

### ISSUE THREAD

**Issue by nunogit** [bridgedb/create-bridgedb-genedb#9]
Check if BioMartSources.tsv is present in resources. If not inform the user and quit gracefully.
Currently the process dies, with a null pointer error.

**Comment by tabbassidaloii** [comment]
Solution would be adding the below line in BioMartAttributes.java file:

line #34: 			if (is == null) System.out.println("[Error]: the BioMartSources.tsv is not present in `src/main/resource/`");

@egonw may I apply it?

**Comment by egonw** [comment]
> @egonw may I apply it?

sounds good to me!
